a_text: just something
untis_file: C:\Users\JohannesLieberherr\Gymnasium Neufeld\Stundenplan - General\21-22_S2\20_Untis\Backup\GPN~31559~21-22_S2~1_20211009_2254_LIJ_Korekktur_LEV_23Fc_GE-MAS_Optimierung_A.untis
initial_file_folder: C:\Users\JohannesLieberherr\Gymnasium Neufeld\Stundenplan - General\21-22_S2\20_Untis\Backup
initial_output_folder: C:\Users\JohannesLieberherr\Gymnasium Neufeld\Stundenplan - General\21-22_S2\52_Kontrolle_Lektionentafeln_Pensen